package com.astroberries.core.state;

public enum StateName {

    NIL, MAINMENU, CHOOSE_GAME, MULTIPLAYER, LEVEL_SELECT, SETTINGS,

    LEVEL_OVERVIEW, PLAYER1, AIMING1, BULLET1, PLAYER2, AIMING2, BULLET2, CAMERA_MOVING_TO_PLAYER_1, CAMERA_MOVING_TO_PLAYER_2, CAMERA_MOVING_TO_COMPUTER_2, PAUSE,

    YOU_LOST, COMPUTER_LOST, PVP_GAME_END,

    COMPUTER2
}